"""auto add phone number to user table

Revision ID: 915d10219d41
Revises: 99469f2d9ea2
Create Date: 2021-11-12 13:08:08.787946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915d10219d41'
down_revision = '99469f2d9ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
